(lang dune 3.23)

(name ocaml_99_problems)

(generate_opam_files true)

(source
 (github pichi/ocaml_99_problems))

(authors "Hynek Vychodil <vychodil.hynek@gmail.com>")

(maintainers "Hynek Vychodil <vychodil.hynek@gmail.com>")

(license MIT)

;(documentation https://url/to/documentation)

(package
 (name ocaml_99_problems)
 (synopsis "99 Ocaml problems solutions")
 (description "99 Ocaml problems solutions by Hynek Vychodil")
 (depends ocaml)
 (tags
  (learning)))
